version: '3.6'
services:
  postgres:
    image: postgis/postgis:14-3.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgis-data-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
  hasura:
    # image: hasura/graphql-engine:v2.0.1
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    volumes:
      - ./hasura-data/migrations:/hasura-migrations
      - ./hasura-data/metadata:/hasura-metadata
volumes:
  db_data:
